apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: inventory
  patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env"
      value: 
      - name: QUARKUS_DATASOURCE_ORDERMGMT_DB_JDBC_URL
        value: jdbc:postgresql://postgresql.thegoodcorner-legacy.svc.cluster.local:5432/ordermanagement
      - name: QUARKUS_HIBERNATE_ORM_INVENTORY_DATABASE_GENERATION
        value: none

# - target:
#     kind: Service
#     name: inventory
#   patch: |-
#     - op: replace
#       path: /metadata/labels/backstage.io/kubernetes-id
#       value: thegoodcorner-dev