---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inventory-preprod
  namespace: janus-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: inventory
spec:
  project: inventory-bootstrap
  source:
    repoURL: https://github.com/RedHat-Summit-Connect-France-2023/inventory-gitops.git
    targetRevision: HEAD
    path: ./overlays/preprod
  destination:
    server: https://kubernetes.default.svc
    namespace: thegoodcorner-preprod
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name|test(".-dockercfg-."))'
      kind: ServiceAccount
    - jqPathExpressions:
        - .spec.host
      group: route.openshift.io
      kind: Route
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy